### ISSUE TITLE
Please update to the latest swing.js

### ISSUE THREAD

**Issue by maeisdev** [peterpeterparker/ionic-swing#10]

**Comment by peterpeterparker** [comment]
thx I have added the features which weren't synced yet respectively https://github.com/gajus/swing/commit/45b578770c2bc0093225674a2049f2ec7d14160f and https://github.com/gajus/swing/commit/9a19ea2fdbf213bb3779b93497088289b355c4cd

**Comment by maedewiza** [comment]
```
[ng] WARNING in ./node_modules/ionic-swing/node_modules/@angular/core/fesm5/core.js 17170:15-36
[ng] Critical dependency: the request of a dependency is an expression
[ng] WARNING in ./node_modules/ionic-swing/node_modules/@angular/core/fesm5/core.js 17182:15-102
[ng] Critical dependency: the request of a dependency is an expression
```
after update to 4.1. The last one 4.0 was working.

**Comment by peterpeterparker** [comment]
@maedewiza I don't face the problem. feel free to provide a sample repo to reproduce the problem
