### ISSUE TITLE
ionic 4.7+

### ISSUE THREAD

**Issue by ocsi94** [peterpeterparker/ionic-swing#14]
Hi!

I have used your plugin in ionic 4 it worked pretty well, but since i upgraded to ionic 4.7+ it throws error.
I already created an example project, so you can check it.
The project just an up-to-date blank ionic project with an ionic-swing plugin implementation.

https://github.com/ocsi94/ionic-swing-angular8Issue

Error :
`NullInjectorError: StaticInjectorError(AppModule)[SwingCardDirective -> ElementRef]: `

Thanks

**Comment by peterpeterparker** [comment]
Are you using Angular v8? I guess that's the reason.

The library should probably be upgraded to v8

**Comment by ocsi94** [comment]
Yeah, I am using angular8, I already tried to upgrade the libraries, but strange things happend, when i test it in the fork  https://github.com/ocsi94/ionic-swing , its works well, but if i pack it and add it to an another project it throws the same error like previous.

**Comment by peterpeterparker** [comment]
@ocsi94 I tried quickly but didn't found the solution. seems that it isn't just a library issue but that the configuration need to be cleaned or adapted

unfortunately I don't have that much time these days, really under pressure with some other project so from my side it might take a while

I'm happy to merge any PR though, if someone could help, that would be cool

Sorry for not being able to do more currently

**Comment by enappd** [comment]
Hi @ocsi94 , 
We were facing the same issues as you in Angular 8. We use this module in one of our products for Tinder style cards. 
We went ahead and followed what you said about [https://github.com/ocsi94/ionic-swing](https://github.com/ocsi94/ionic-swing) fork working nicely as a separate project. So we just copied the module as a component in the parent project, and imported it in other pages from the copied module, not from the node-modules. And it worked ! (for whatever reasons)
Thanks for the hint !

**Comment by ocsi94** [comment]
Hi @enappd ,
Yeah, if you do it like, copy the component it will work, I also use it like you.
The problem was the ng-packagr. If you pack it an want to install as an npm module it won't work.
They solved the issue in the version of 5.5.1.
I will create a pull request, if i ready with my other things.

**Comment by ocsi94** [comment]
Pull request created.
https://github.com/fluster/ionic-swing/pull/16
