### ISSUE TITLE
Hey I have followed your tutorial to build a swing cards, But I am facing a transpilation problem,Please any support :D!

### ISSUE THREAD

**Issue by reda-z** [peterpeterparker/ionic-swing#7]
typescript: ...les/ionic-swing/node_modules/@angular/core/src/render3/interfaces/container.d.ts, line: 35
            A computed property name in an interface must directly refer to a built-in symbol.

      L35:   * This allows us to jump from a container to a sibling container or component
      L36:   * view with the same parent, so we can remove listeners efficiently.

[18:33:37]  typescript: ...les/ionic-swing/node_modules/@angular/core/src/render3/interfaces/container.d.ts, line: 40
            A computed property name in an interface must directly refer to a built-in symbol.

      L40:   * Queries active for this container - all the views inserted to / removed from
      L41:   * this container are reported to queries referenced here.

[18:33:37]  typescript: ...les/ionic-swing/node_modules/@angular/core/src/render3/interfaces/container.d.ts, line: 45
            A computed property name in an interface must directly refer to a built-in symbol.

      L45:   * A list of the container's currently active child views. Views will be inserted
      L46:   * here as they are added and spliced from here when they are removed. We need

**Comment by peterpeterparker** [comment]
could you be more specific and give more context? 
also what are your `ionic info`?
wish version of the library are you using?

**Comment by reda-z** [comment]
I am building an app with the same swing effect in tinder so I have used ionic-swing module for that, The problem is that when I have followed the tutorial made when I run ionic serve I get this error.

![ionic_serve_issue](https://user-images.githubusercontent.com/24222080/46526370-f74ca100-c885-11e8-8c04-e136c5da3d81.png)

I have pushed the code in this repository : https://github.com/reda-z/ionic-swing


IONIC INFO : 


cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v10.8.0
    npm               : 6.2.0
    OS                : Linux 4.15


Thanks in advance

**Comment by peterpeterparker** [comment]
1. You didn't published your code to https://github.com/reda-z/ionic-swing, it's just a starter app there aren't any references to this library

2. Since you are using Ionic v3 you probably have to stick to v0.2.0 of this library because I migrated it to Angular v6 in its v2 (https://github.com/fluster/ionic-swing/blob/master/CHANGELOG.md)

**Comment by reda-z** [comment]
Sorry it was a push issue , Can you check it now please .

**Comment by peterpeterparker** [comment]
Thx that confirm what I said in my 2nd comment here above

**Comment by reda-z** [comment]
Thank you , I have downgraded ionic-swing to v0.2.0 but I can't use SwingStackComponent, SwingCardComponent components.The import says these classes don't exist.

**Comment by peterpeterparker** [comment]
With Ionic v3 and ionic-swing v0.2.0

    import {StackConfig, DragEvent, SwingStackComponent, SwingCardComponent, Direction} from 'ionic-swing';
    
    @ViewChild('mySwingStack') swingStack: SwingStackComponent;
    @ViewChildren('mySwingCards') swingCards: QueryList<SwingCardComponent>;

Should be ok I checked my old app

**Comment by peterpeterparker** [comment]
Close inactivity
