### ISSUE TITLE
Integration with new Gestures V4

### ISSUE THREAD

**Issue by kalicki** [peterpeterparker/ionic-swing#8]
Hey.

The Ionic team has released a new layer of code for gestures on V4, without using hammer.js
I created these issues to analyze the viability of a new integration.

Ref: https://github.com/ionic-team/ionic/tree/master/core/src/utils/gesture

Thanks.

**Comment by peterpeterparker** [comment]
Sure I'm not against the idea. If you find it cool and would like to submit a PR, go for it ;)

**Comment by Proudfoot1** [comment]
Hello sir. I saw your advice @ https://github.com/ionic-team/ionic/issues/14883 and I was wondering if that solves this issue and we should do that in order to use this module or if we should stick to the readme and import hammer.js

**Comment by peterpeterparker** [comment]
@Proudfoot you need to import `hammer` and if you are facing the same issue as the one described in the issue https://github.com/ionic-team/ionic/issues/14883 you are linking  then yes you need to implement the workaround I displayed there https://github.com/ionic-team/ionic/issues/14883#issuecomment-411784729 was mandatory for my app.

But plz don't comment further here, none of this is linked to this feature request

**Comment by Proudfoot1** [comment]
Thanks @peterpeterparker, I researched a lot and this is the best and most current Angular module there is for this functionality.

**Comment by peterpeterparker** [comment]
I don't maintain the plugin anymore and therefore I'm not going to develop any improvements.

If someone is interested to fork the project and continue it, let me know, I'll be happy to add a note in the README about it.
