### ISSUE TITLE
Error: Global and doMove

### ISSUE THREAD

**Issue by kalicki** [peterpeterparker/ionic-swing#9]
Hey.

I have two problems. I don't know what it may be, but it looks like the Hammer.

I follow the guide: 
1 - `app.components.ts` contains `import 'hammerjs';`
2- `recipes.module.ts` contains `IonicSwingModule`
3- `recipes.html` contais this: https://gist.github.com/kalicki/ea033f76db2e7276f238b48ae0b84c2c
4- `recipes.ts` contains this: https://gist.github.com/kalicki/1029d5e04b1f969052b33592fb64cde3

1:  is `ERROR ReferenceError: "global is not defined"`
![captura de tela 2018-12-13 as 12 33 25](https://user-images.githubusercontent.com/3674885/49945644-7d174900-fed4-11e8-93d7-b073ff1d0702.png)

2: is `ERROR TypeError: "doMove is not a function"`
![captura de tela 2018-12-13 as 12 33 45](https://user-images.githubusercontent.com/3674885/49945646-7dafdf80-fed4-11e8-8cd8-28f550e2076e.png)

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/kalicki/.nvm/versions/node/v10.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.11.2
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.2
   @ionic/angular-toolkit        : 1.2.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.11
   @capacitor/core           : 1.0.0-beta.11

System:

   NodeJS : v10.12.0 (/Users/kalicki/.nvm/versions/node/v10.12.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by peterpeterparker** [comment]
hey @kalicki, just a click msg because I've got no time right now, but I will try to have a look in the next couple of days

if you could provide the all sample repo that would be helpful

**Comment by kalicki** [comment]
Peter Parker haha, i upload example on stackblitz: https://stackblitz.com/edit/github-hbuzk3-kddvrp?file=src%2Fapp%2Fhome%2Fhome.page.ts

Tks

**Comment by kalicki** [comment]
For some reason, sometimes it works in Chrome but in Firefox does not work.

**Comment by peterpeterparker** [comment]
Ok so first of all, it works fine in Firefox, just tested my app in Firefox 63, everything went fine

About reliability, same in my app, there is no reliability problem

Then I can't start your Stackblitz, when I open it hangs on "Starting dev server"

But beside that, maybe the problem is the fact that you fetch data on init where the dom is not actually ready that's why the card might not be able to be created? could you try to move your `this.recipeService.getRecipeList()` from `ngOnInit` to `ionViewWillEnter` for example?

**Comment by DexterHuang** [comment]
how can this be fixed? I am having the exact same issue here...
[EDIT]
Hey, I have found the solution to this issue.
just add `(window as any).global = window;` to the end of `polyfills.ts`;

**Comment by peterpeterparker** [comment]
@DexterHuang do you want to add it to the readme? if yes, would you like to submit a PR?
